# Generated by Django 6.0.3 on 2026-05-10 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=255)),
                ('code_barre', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('sous_categorie', models.CharField(blank=True, max_length=255, null=True)),
                ('famille', models.CharField(blank=True, max_length=255, null=True)),
                ('prix_achat_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_vente_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('stock_initial', models.IntegerField(default=0)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('seuil_minimum', models.IntegerField(default=0)),
                ('seuil_critique', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.entreprise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entreprise', 'code_barre'), name='unique_code_barre_par_entreprise')],
            },
        ),
    ]
