# Generated by Django 6.0.3 on 2026-05-10 18:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('email', models.EmailField(error_messages={'invalid': "Format d'email invalide.", 'unique': 'Cet email est déjà utilisé.'}, max_length=254, unique=True)),
                ('date_anniversaire', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=10, null=True)),
                ('telephone', models.CharField(blank=True, error_messages={'unique': 'Ce numéro est déjà utilisé.'}, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('code_barre', models.CharField(max_length=50)),
                ('points_fidelite', models.IntegerField(default=0)),
                ('panier_moyen', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categorie_preferee', models.CharField(blank=True, max_length=255, null=True)),
                ('derniere_visite', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.entreprise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entreprise', 'code_barre'), name='unique_code_barre_client_par_entreprise')],
            },
        ),
    ]
