# Generated by Django 6.0.3 on 2026-05-07 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date_livraison_prevue',
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='designation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
